### PR TITLE
replace explicit int/int32 by long, which is provided by NativeCall now

### PR DESCRIPTION
**Pull request by FROGGS**
This also means we can remove the custon Build.pm installer hook.

It passes on 64bit and 32bit linux:
```
froggs@ubuntu-x86:~/dev/P6-Compress-Zlib-Raw$ perl6-m -I../p6-Inline-C/lib -Ilib t/01-basic.t
1..7
ok 1 - Compiled
ok 2 - Got zlib version (1.2.8)
ok 3 - Compressed data
ok 4 - Compressed data is different than input
ok 5 - Uncompressed data
ok 6 - Got correct original data size...
ok 7 - ...And got the right data!
```

```
froggs@ubuntu-x86_64:~/dev/p6-Compress-Zlib-Raw$ perl6-m -I../p6-Inline-C/lib -Ilib t/01-basic.t 
1..7
ok 1 - Compiled
ok 2 - Got zlib version (1.2.8)
ok 3 - Compressed data
ok 4 - Compressed data is different than input
ok 5 - Uncompressed data
ok 6 - Got correct original data size...
ok 7 - ...And got the right data!
```

### CODE REVIEW

**Comment by FROGGS** [comment]
Btw, the on 64bit ubuntu I can also just load the `libz.so.1`, so I am wondering if we always should look for that library in case the `$*VM.config<dll>` equals `so`.

**Comment by FROGGS** [comment]
That seems to agree: http://refspecs.linuxbase.org/LSB_3.1.1/LSB-Core-generic/LSB-Core-generic/libz.html

```
14.2. Interfaces for libz

Table 14-1 defines the library name and shared object name for the libz library

Table 14-1. libz Definition
Library:	libz
SONAME:	libz.so.1
```

**Comment by FROGGS** [comment]
Btw:
```
froggs@ubuntu-x86_64:~$ perl6-m -e 'use NativeCall; say nativesizeof(OpaquePointer)'
8
froggs@ubuntu-x86_64:~$ perl6-m -e 'use NativeCall; say nativesizeof(long)'
8
froggs@ubuntu-x86_64:~$ perl6-m -e 'use NativeCall; say nativesizeof(int32)'
4
froggs@ubuntu-x86_64:~$ perl6-m -e 'use NativeCall; say nativesizeof(int8)'
1
froggs@ubuntu-x86_64:~$ perl6-m -e 'use NativeCall; say nativesizeof(int)'
8
```

```
froggs@ubuntu-x86:~$ perl6-m -e 'use NativeCall; say nativesizeof(OpaquePointer)'
4
froggs@ubuntu-x86:~$ perl6-m -e 'use NativeCall; say nativesizeof(long)'
4
froggs@ubuntu-x86:~$ perl6-m -e 'use NativeCall; say nativesizeof(int32)'
4
froggs@ubuntu-x86:~$ perl6-m -e 'use NativeCall; say nativesizeof(int8)'
1
froggs@ubuntu-x86:~$ perl6-m -e 'use NativeCall; say nativesizeof(int)'
8
```

**Comment by retupmoca** [comment]
Oh, that will be very handy!

**Comment by FROGGS** [comment]
rakudo HEAD provides nativesizeof() now... That means that when we can put Blobs into CStructs you dont need Inline::C anymore... (which also means that the user does not need a Compiler anymore, in theory at least).

**Pull request merged**
